version: '3'
services:

  client:
    image: isafe-client-dev-i
    container_name: isafe-client-dev-c
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - node_modules_client:/client/node_modules/
    environment:
      - NODE_ENV=development

  server:
    image: isafe-server-dev-i
    container_name: isafe-server-dev-c
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./server:/server
      - node_modules_server:/server/node_modules/
    environment:
      - NODE_ENV=development
      - PORT=3001

  db:
    ports:
      - "27017:27017"

volumes:
  node_modules_client:
  node_modules_server: