version: '3'
services:

  client:
    depends_on:
      - server
    build:
      context: ./client
    networks:
      - my-net

  server:
    depends_on:
      - db
    build:
      context: ./server
    networks:
      - my-net

  db:
    image: mongo
    volumes:
      - db_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    networks:
      - my-net

volumes:
  db_data:


networks:
  my-net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400