version: '3'
services:

  client:
    image: isafe-client-prod-i
    container_name: isafe-client-prod-c
    build:
      dockerfile: Dockerfile.prod
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production

  server:
    image: isafe-server-prod-i
    container_name: isafe-server-prod-c
    build:
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - PORT=4000

  db:
    ports:
      - "27017:27017"